project:
  output-dir: docs/en
  resources: images
  
  
# Set language
lang: en

# Set bibliography source
bibliography: bibliography.bib

# Set website config and logos
website:
  title: "PPCI - PrototypePHP for CodeIgniter"
  ## Navbar menu
  navbar:
    logo:  images/ci-logo.png
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - text: Installation
        menu: 
          - text: Installation
            href: installation.qmd
          - text: Migrate from PrototypePhp
            href: migration.qmd
          - text: multi-instances
            href: multi-instance.qmd
      - text: Technical documentation
        menu:
          - text: Generic principles
            href: principes.qmd
          - text: Parameters
            href: parameters.qmd
          - text: Identification
            href: identification.qmd
          - text: Right management
            href: rights.qmd
          - text: Routes and controllers
            href: controllers.qmd
          - text: Libraries
            href: libraries.qmd
          - text: Views
            href: views.qmd
          - text: Database access
            href: model.qmd
          - text: HTML pages
            href: smarty.qmd
          - text: Functions and services
            href: functions.qmd
          - text: Localization
            href: locale.qmd
          - text: Command line
            href: command-line.qmd
    right:
      - href: ../fr
        text: français
      - text: "Other links"
        icon: globe
        menu: 
          - text: Quarto
            href: https://quarto.org
          - text: "INRAE"
            href: https://www.inrae.fr/
  ## Footer
  page-footer:
    left: |
        [![](https://www.inrae.fr/themes/custom/inrae_socle/public/images/etat_logo.svg){width=100px}![](https://www.inrae.fr/themes/custom/inrae_socle/logo.svg){width=100px}](https://www.inrae.fr/)
    right: |
        [![](https://eabx.bordeaux-aquitaine.hub.inrae.fr/var/hub_internet_c22_eabx/storage/images/_aliases/medium/4/6/5/1/41564-1-fre-FR/c982775f2366-logo-eabx.jpg){width=100px}](https://eabx.bordeaux-aquitaine.hub.inrae.fr/)
    center: 
      - text: LEGAL NOTICE
        icon: book
        href: legal_notice.qmd
  ## Margin
  margin-footer: |
    Made with [![](https://github.com/SebastienBoutry/inrae-project-website/blob/main/images/extension-logo.png?raw=true){width="50px"}](https://github.com/SebastienBoutry/inrae-project-website)
  