::: {.content-visible when-profile="french"}

# Support des langues

Actuellement, le moteur ne gère que le français (langue par défaut) et l'anglais.

Les traductions sont réalisées avec *gettext*. Elles sont stockées dans `app/Language/locales`, avec :

- à la racine :
  - *lang.po* : fichier brut contenant les traductions
  - *generate_po.sh* : script récupérant les libellés à traduire dans les fichiers php, les templates Smarty et dans le menu (fichier xml) et créant le fichier *lang.po*
  - compile.sh : script créant le fichier lang.mo (compilé) à partir des traductions présentes dans *lang.po*, et recopiant ce fichier dans le sous-dossier suivant
- *en/LC_MESSAGES* : dossier correspondant à la langue à afficher, qui contient le fichier *lang.mo*.

## Mettre en place les traductions

Le serveur doit être configuré pour supporter la langue à afficher. Pour cela :

- éditez le fichier `/etc/locale.gen`
- décommentez la ligne `en_GB.UTF-8`
- lancez ces commandes :

```bash
locale-gen
systemctl restart apache2
```

Cette opération n'est à réaliser qu'une seule fois.

Pour créer les traductions :

- lancez le script `generate_po.sh` pour créer le fichier *lang.po*. Les anciennes traductions sont conservées.
- éditez le fichier *lang.po* avec le programme *poedit*
- compilez le fichier avec le script `compile.sh`. Le script va générer le fichier *lang.mo*, puis le recopier dans le dossier *en/LC_MESSAGES*

:::

::: {.content-visible when-profile="english"}
# Language support

Currently, the engine only supports French (default language) and English.

Translations are made with *gettext*. They are stored in `app/Language/locales`, with:

- at the root:
- *lang.po*: raw file containing the translations
- *generate_po.sh*: script retrieving the labels to be translated in the php files, Smarty templates and in the menu (xml file) and creating the *lang.po* file
- compile.sh: script creating the lang.mo file (compiled) from the translations present in *lang.po*, and copying this file into the following subfolder
- *en/LC_MESSAGES*: folder corresponding to the language to be displayed, which contains the *lang.mo* file.

## Set up translations

The server must be configured to support the language to be displayed. To do this:

- edit the file `/etc/locale.gen`
- uncomment the line `en_GB.UTF-8`
- run these commands:

```bash
locale-gen
systemctl restart apache2
```

This operation only needs to be done once.

To create the translations:

- run the script `generate_po.sh` to create the file *lang.po*. The old translations are kept.
- edit the file *lang.po* with the program *poedit*
- compile the file with the script `compile.sh`. The script will generate the file *lang.mo*, then copy it into the folder *en/LC_MESSAGES*
:::