::: {.content-visible when-profile="french"}

# Gestion du multi-instances

## Créer le dossier dédié à l'instance

Créez un dossier dédié à l'instance dans l'arborescence du serveur, par exemple `/var/www/app/instancename`, puis créez les fichiers nécessaires pour assurer la séparation des instances :

```bash
# Dossier contenant le code de l'application
APP=/var/www/app
# Dossier comprenant les paramètres spécifiques de l'instance
FOLDER="/var/www/instances/instancename"
mkdir -P $FOLDER
chmod g+r $FOLDER
cd $FOLDER
mkdir temp
# Nouvelles cles cryptographiques
openssl genpkey -algorithm rsa -out id_app -pkeyopt rsa_keygen_bits:2048
openssl rsa -in id_app -pubout -out id_app.pub
# Recopie du fichier de parametrage
cp $APP/env .env
# Mise à niveau des droits
chmod -R g+r .
chmod g+w temp
chown www-data id_app
```

le dossier *temp* est le dossier dans lequel l'application va générer tous les fichiers avant leur envoi au navigateur. Pour éviter les risques de collision entre deux instances, il est vivement recommandé que chacune dispose de son propre espace.

:::

::: {.content-visible when-profile="english"}
# Multi-instance management

## Create the dedicated instance folder

Create an instance folder in the server tree, for example `/var/www/app/instancename`, then create the files needed to keep the instances separate:

```bash
# Folder containing the application code
APP=/var/www/app
# Folder containing the specific parameters of the instance
FOLDER="/var/www/instances/instancename"
mkdir -P $FOLDER
chmod g+r $FOLDER
cd $FOLDER
mkdir temp
# New cryptographic keys
openssl genpkey -algorithm rsa -out id_app -pkeyopt rsa_keygen_bits:2048
openssl rsa -in id_app -pubout -out id_app.pub
# Copy the configuration file
cp $APP/env .env
# Upgrade rights
chmod -R g+r .
chmod g+w temp
chown www-data id_app
```

the *temp* folder is the folder in which the application will generate all the files before sending them to the browser. To avoid the risk of collision between two instances, it is strongly recommended that each has its own space.
:::

::: {.content-visible when-profile="french"}

## Mettre à niveau du site virtuel Apache

Rajoutez, dans la description du site virtuel (fichier `moninstance.conf`, dans `/etc/apache2/sites-available`) :

```apache
<VirtualHost *:443>
    (...)
    DocumentRoot /var/www/app
    setenv envPath /var/www/instances/instancename
    (...)  
```

## Modifier les paramètres

Éditez le fichier `/var/www/instances/instancename/.env` :

```env
app.baseURL = 'https://myinstance.mysociety.com'
BASE_DIR = "/var/www/instances/instancename"
app.privateKey = ${BASE_DIR}/id_app
app.pubKey = ${BASE_DIR}/id_app.pub
# directory to store temp files and sessions
TEMP = "${BASE_DIR}/temp"
#TEMP for multinstance
app.APP_temp = "${TEMP}"
session.savePath = "{$TEMP}/sessions"
database.default.hostname = localhost
database.default.database = dbname_instance
database.default.username = login_instance
database.default.password = password_instance
```

Les sessions PHP sont maintenant stockées dans un sous-dossier de temp, pour limiter les risques de vol de sessions en mode multi-instances.

Vérifiez également le mode d'identification par défaut, et adaptez-le le cas échéant.

## Adapter les scripts lancés en ligne de commande

Si vous utilisez des scripts qui sont exécutés en ligne de commande, par exemple programmés à horaires réguliers (crontab), vous devrez modifier le script de lancement :

```bash
#!/bin/bash
export envPath=/var/www/instances/instancename
cd $envPath/public
php index.php monscript
```
où *monscript* correspond à la route à appeler.

La variable `envPath` est disponible dans `$_SERVER`.

:::

::: {.content-visible when-profile="english"}
## Upgrading the Apache virtual site

In the virtual site description (`myinstance.conf` file, in `/etc/apache2/sites-available`), add :

```apache
<VirtualHost *:443>
(...)
DocumentRoot /var/www/app
setenv envPath /var/www/instances/instancename
(...) 
```

## Modifying the parameters

Edit the `/var/www/instances/instancename/.env` file:

```env
app.baseURL = ‘https://myinstance.mysociety.com’
BASE_DIR = ‘/var/www/instances/instancename
app.privateKey = ${BASE_DIR}/id_app
app.pubKey = ${BASE_DIR}/id_app.pub
# directory to store temp files and sessions
TEMP = "${BASE_DIR}/temp"
#TEMP for multinstance
app.APP_temp = "${TEMP}"
session.savePath = "{$TEMP}/sessions"
database.default.hostname = localhost
database.default.database = dbname_instance
database.default.username = login_instance
database.default.password = password_instance
```

PHP sessions are now stored in a subfolder of temp, to limit the risk of session theft in multi-instance mode.

Also check the default login mode, and adapt it if necessary.

## Adapt scripts run on the command line

If you use scripts that are run from the command line, for example scripts that are scheduled to run at regular times (crontab), you will need to modify the script loader:

```bash
#!/bin/bash
export envPath=/var/www/instances/instancename
cd $envPath/public
php index.php myscript
```

where *myscript* is the route to call.

The `envPath` variable is available in `$_SERVER`.
:::

::: {.content-visible when-profile="french"}


## Technique : modifications apportées au code pour gérer le multi-instances

La fin du fichier index.php est modifié ainsi : 

```php
//exit(CodeIgniter\Boot::bootWeb($paths));
require FCPATH. '../vendor/equinton/ppci/src/BootApp.php';
exit (CodeIgniter\BootApp::bootweb($paths));
```

Et la classe `BootApp` contient ce code :
:::

::: {.content-visible when-profile="english"}
## Technical: changes made to the code to manage multi-instances


The end of the index.php file is modified as follows: 


```php
//exit(CodeIgniter\Boot::bootWeb($paths));
require FCPATH. '../vendor/equinton/ppci/src/BootApp.php';
exit (CodeIgniter\BootApp::bootweb($paths));
```

And the `BootApp` class contains this code:
:::

```php
<?php

namespace CodeIgniter;

use CodeIgniter\Boot;
use Config\Paths;
use CodeIgniter\Config\DotEnv;

class BootApp extends Boot {

    protected static function loadDotEnv(Paths $paths): void
    {
        require_once $paths->systemDirectory . '/Config/DotEnv.php';
        if (is_file($file = $_SERVER["envPath"] . DIRECTORY_SEPARATOR . ".env") && is_readable($file)) {
            (new DotEnv($_SERVER["envPath"],".env"))->load();
        } else {
            (new DotEnv($paths->appDirectory . '/../'))->load();
        }
    }
}
```
::: {.content-visible when-profile="french"}
**Attention :** l'utilisation d'un fichier .env placé ailleurs qu'à la racine de l'application empêche le fonctionnement des outils de débogage de CodeIgniter (mode développement).

:::

::: {.content-visible when-profile="english"}
**Warning:** the use of an .env file placed elsewhere than at the root of the application prevents CodeIgniter's debugging tools from working (development mode).
:::