::: {.content-visible when-profile="french"}
# Paramètres de l'application

Les paramètres sont définis dans plusieurs fichiers : `app/Config/App.php` et ceux présents dans le dossier `vendor/equinton/ppci/src/Config`.

S'ils peuvent tous être modifiés lors de chaque implémentation en utilisant le fichier `.env`, à la racine de l'application, certains ne devraient pas être modifiés par ce mécanisme.

Les paramètres dans le fichier .env sont préfixés soit par `app.`, soit par `Ppci\Config\Class.`, en fonction de leur origine. Le fichier *env* contient l'ensemble des variables pouvant être modifiées lors de l'implémentation d'une instance du logiciel.
:::

::: {.content-visible when-profile="english"}
# Application parameters

The parameters are defined in several files: *app/Config/App.php* and those defined in the folder *vendor/equinton/ppci/src/Config*.

While they can all be modified during each implementation using the `.env` file at the root of the application, some should not be modified using this mechanism.

Parameters in the .env file are prefixed with either `app.` or `Ppci\Config\Class.`, depending on their origin. The *env* file contains all the variables that can be modified when an instance of the software is implemented.
:::

::: {.content-visible when-profile="french"}
## Paramètres génériques

+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| Paramètre (avec le radical utilisé dans le fichier .env) | Description                                                                                                                                                                                                                                                                               | Valeur par défaut                                     | Modifiable dans .env                                                           |
+==========================================================+===========================================================================================================================================================================================================================================================================================+=======================================================+================================================================================+
| app.baseURL                                              | Adresse de l'instance                                                                                                                                                                                                                                                                     |                                                       | obligatoire                                                                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| BASE_DIR                                                 | variable utilisée dans .env, pour indiquer le chemin d'accès à l'application                                                                                                                                                                                                              | p\. e. "/var/www/collec2"                             | obligatoire                                                                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| FRONT_DIR                                                | variable utilisée dans .env, pour indiquer le chemin d'accès au dossier public, la base des pages web                                                                                                                                                                                     | \${BASE_DIR}/public                                   | en principe, non                                                               |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.defaultLocale                                        | Langue par défaut dans l'instance                                                                                                                                                                                                                                                         | fr                                                    | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.supportedLocales                                     | Langues gérées par l'application                                                                                                                                                                                                                                                          | \['fr','en'\]                                         | possible, sous réserve que d'autres langues soient intégrées dans le framework |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.version                                              | Version de l'application                                                                                                                                                                                                                                                                  |                                                       | jamais                                                                         |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.versionDate                                          | Date de création de la version                                                                                                                                                                                                                                                            |                                                       | jamais                                                                         |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.dbversion                                            | Version de la base de données. La version doit également exister dans la table dbversion de la base de données                                                                                                                                                                            |                                                       | jamais                                                                         |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| databaseSchemaFile                                       | Chemin où est placé le png décrivant les tables de la base de données                                                                                                                                                                                                                     | p\. e. : ROOTPATH . "documentation/collec-schema.png" | jamais                                                                         |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.logDuration                                          | Durée, en jours, de conservation des logs dans la table logs                                                                                                                                                                                                                              | 365                                                   | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.privateKey                                           | emplacement de la clé privée utilisée pour les opérations de chiffrement ou déchiffrement                                                                                                                                                                                                 | p\. e., \${BASE_DIR}/id_collec                        | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.pubKey                                               | emplacement de la clé publique utilisée pour les opérations de chiffrement ou déchiffrement                                                                                                                                                                                               | p\. e. \${BASE_DIR}/id_collec.pub                     | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| session.expiration                                       | Durée de la session, en secondes                                                                                                                                                                                                                                                          | 14400 (4 heures)                                      | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.APPLI_absolute_session                               | Durée maxi de la session, en secondes                                                                                                                                                                                                                                                     | 36000 (10 heures)                                     | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| logger.threshold                                         | Seuil de déclenchement des erreurs                                                                                                                                                                                                                                                        | 4                                                     | jamais                                                                         |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.APP_mail                                             | email de l'application                                                                                                                                                                                                                                                                    | mail\@mysociety.com                                   | obligatoire                                                                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.MAIL_enabled                                         | Si à 1, l'envoi de mails est activé                                                                                                                                                                                                                                                       | 1                                                     | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.MAIL_param.from                                      | idem APP_mail                                                                                                                                                                                                                                                                             | mail\@mysociety.com                                   | obligatoire                                                                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.MAIL_param.mailDebug                                 | Si à 1, affiche le contenu du mail à l'écran plutôt que de l'envoyer                                                                                                                                                                                                                      | 0                                                     | en développement uniquement                                                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.docroot                                              | URL de base de la doc en ligne                                                                                                                                                                                                                                                            |                                                       | cf. [la configuration du menu](smarty.html#gestion-du-menu)                    |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
| app.checkRelease                                         | Si à 1, interroge le serveur GIT (Github ou Gitlab) pour connaître la dernière version disponible, et si la version est différente de celle enregistrée (app.version), affiche un message à l'écran. Les paramètres spécifiques pour l'interrogation sont décrits dans le fichier App.php | 0                                                     | possible                                                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------+
:::

::: {.content-visible when-profile="english"}
## Generic parameters

+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| # Parameter (with the radical used in the .env file) | # Description                                                                                                                                                                                                                                                       | # Default value                                    | # Modifiable in .env                                                      |
|                                                      |                                                                                                                                                                                                                                                                     |                                                    |                                                                           |
| app.baseURL                                          | Instance address                                                                                                                                                                                                                                                    |                                                    | mandatory                                                                 |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| BASE_DIR                                             | variable used in .env, to indicate the path to the application                                                                                                                                                                                                      | e.g. "/var/www/collec2"                            | mandatory                                                                 |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| FRONT_DIR                                            | variable used in .env, to indicate the path to the public folder, the base of web pages                                                                                                                                                                             | \${BASE_DIR}/public                                | in principle, no                                                          |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.defaultLocale                                    | Default language in the instance                                                                                                                                                                                                                                    | fr                                                 | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.supportedLocales                                 | Languages ​​managed by the application                                                                                                                                                                                                                                | \['fr','en'\]                                      | possible, provided that other languages ​​are integrated into the framework |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.version                                          | Application version                                                                                                                                                                                                                                                 |                                                    | never                                                                     |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.versionDate                                      | Version creation date                                                                                                                                                                                                                                               |                                                    | never                                                                     |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.dbversion                                        | Database version. The version must also exist in the database dbversion table                                                                                                                                                                                       |                                                    | never                                                                     |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| databaseSchemaFile                                   | Path where the png describing the database tables is placed                                                                                                                                                                                                         | e.g.: ROOTPATH ​​. "documentation/collec-schema.png" | never                                                                     |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.logDuration                                      | Duration, in days, to keep logs in the logs table                                                                                                                                                                                                                   | 365                                                | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.privateKey                                       | location of the private key used for encryption or decryption operations                                                                                                                                                                                            | e.g., \${BASE_DIR}/id_collec                       | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.pubKey                                           | location of the public key used for encryption or decryption operations                                                                                                                                                                                             | e.g. \${BASE_DIR}/id_collec.pub                    | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| session.expiration                                   | Session duration, in seconds                                                                                                                                                                                                                                        | 14400 (4 hours)                                    | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.APPLI_absolute_session                           | Maximum session duration, in seconds                                                                                                                                                                                                                                | 36000 (10 hours)                                   | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| logger.threshold                                     | Error trigger threshold                                                                                                                                                                                                                                             | 4                                                  | never                                                                     |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.APP_mail                                         | application email                                                                                                                                                                                                                                                   | mail\@mysociety.com                                | mandatory                                                                 |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.MAIL_enabled                                     | If set to 1, sending emails is enabled                                                                                                                                                                                                                              | 1                                                  | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.MAIL_param.from                                  | same as APP_mail                                                                                                                                                                                                                                                    | mail\@mysociety.com                                | mandatory                                                                 |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.MAIL_param.mailDebug                             | If set to 1, display the content of the email on the screen instead of sending it                                                                                                                                                                                   | 0                                                  | development only                                                          |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.docroot                                          | URL root of the online doc                                                                                                                                                                                                                                          |                                                    | cf. [the menu configuration](smarty.html#menu-management)                 |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
| app.checkRelease                                     | If set to 1, queries the GIT server (Github or Gitlab) for the latest version available, and if the version is different from the one saved (app.version), displays a message on the screen. The specific parameters for querying are described in the App.php file | 0                                                  | possible                                                                  |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------+
:::

::: {.content-visible when-profile="french"}
## Paramètres de connexion à la base de données

+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| Paramètre                   | Description                                                                 | Valeur par défaut      | Modifiable dans .env |
+=============================+=============================================================================+========================+======================+
| database.default.hostname   | nom ou adresse du serveur                                                   | localhost              | oui                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.database   | nom de la base de données                                                   |                        | oui                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.username   | nom du compte de connexion                                                  |                        | oui                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.password   | mot de passe associé                                                        |                        | oui                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.DBDriver   | Nom du pilote                                                               | Postgre                | non                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.port       | port de connexion                                                           | 5432                   | oui                  |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.searchpath | liste des schémas utilisés dans la base de données, séparés par une virgule | p\. e. col,gacl,public | en principe, non     |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+
| database.default.charset    | jeu de caractères utilisé dans la base de données                           | utf8                   | jamais               |
+-----------------------------+-----------------------------------------------------------------------------+------------------------+----------------------+

## Paramètres liés à l'identification des utilisateurs

Voir la page [identification](identification.qmd).
:::

::: {.content-visible when-profile="english"}
## Database Connection Parameters

+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| Parameter                   | Description                                          | Default              | Can be changed in .env |
+=============================+======================================================+======================+========================+
| database.default.hostname   | server name or address                               | localhost            | yes                    |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.database   | database name                                        |                      | yes                    |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.username   | login account name                                   |                      | yes                    |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.password   | associated password                                  |                      | yes                    |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.DBDriver   | driver name                                          | Postgre              | no                     |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.port       | connection port                                      | 5432                 | yes                    |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.searchpath | comma-separated list of schemas used in the database | e.g. col,gacl,public | normally no            |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+
| database.default.charset    | character set used in the database                   | utf8                 | never                  |
+-----------------------------+------------------------------------------------------+----------------------+------------------------+

## Settings related to user identification

See the [identification](identification.qmd) page.
:::

::: {.content-visible when-profile="french"}
## Paramètres de sécurité

Ces paramètres influent sur le fonctionnement général de l'application, et ne devraient être modifiés qu'en toute connaissance de cause.

+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Paramètre                                                     | Description                                                                                                                                                                              | Valeur par défaut | Modifiable dans .env                                                                                                                       |
+===============================================================+==========================================================================================================================================================================================+===================+============================================================================================================================================+
| Ppci\Config\IdentificationConfig.CONNECTION_max_attempts      | Nombre d'essais de mots de passe avant blocage du compte                                                                                                                                 | 5                 | Non recommandé                                                                                                                             |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.CONNECTION_blocking_duration | Durée en secondes de blocage du compte. La durée est réinitialisée à chaque tentative. Est utilisé uniquement pour l'identification BDD ou LDAP                                          | 600               | Non recommandé                                                                                                                             |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.APP_passwordMinLength        | Longueur minimale du mot de passe, pour l'identification BDD                                                                                                                             | 12                | Valeur à adapter selon les recommandations CNIL                                                                                            |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.APPLI_lostPassword           | Si à 1, l'application autorise l'utilisateur à réinitialiser son mot de passe en cas de perte (identification BDD)                                                                       | 1                 | Nécessite l'activation de l'envoi des mails                                                                                                |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.tokenIdentityValidity        | Durée de validité du jeton généré automatiquement lors de l'identification (hors HEADER). Le jeton permet à l'utilisateur de se reconnecter automatiquement tant que le jeton est valide | 36000 (10 heures) |                                                                                                                                            |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.adminSessionDuration         | Durée en secondes de validité de la session "admin". Une fois que la durée est expirée, le code TOTP est redemandé.                                                                      | 600 (10 minutes)  | Non recommandé                                                                                                                             |
|                                                               |                                                                                                                                                                                          |                   |                                                                                                                                            |
|                                                               | Le compteur se réinitialise à chaque accès à un module "admin"                                                                                                                           |                   |                                                                                                                                            |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.GACL_disable_new_right       | Si à 1, la création d'un nouveau droit est inhibée                                                                                                                                       | 1                 | Jamais. Les droits sont définis au moment du développement de l'application, toucher à ce paramètre peut entraîner des effets indésirables |
+---------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: {.content-visible when-profile="english"}
These settings affect the overall functioning of the application, and should only be changed with full knowledge of the consequences.

+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Parameter                                                     | Description                                                                                                                                                                       | Default          | Can be changed in .env                                                                                       |
+===============================================================+===================================================================================================================================================================================+==================+==============================================================================================================+
| Ppci\Config\IdentificationConfig.CONNECTION_max_attempts      | Number of password attempts before account lockout                                                                                                                                | 5                | Not recommended                                                                                              |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.CONNECTION_blocking_duration | Account block duration in seconds. The duration is reset with each attempt. Used only for database or LDAP authentication                                                         | 600              | Not recommended                                                                                              |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.APP_passwordMinLength        | Minimum password length for database identification                                                                                                                               | 12               | Value to be adjusted according to CNIL recommendations                                                       |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.APPLI_lostPassword           | If set to 1, the application allows the user to reset their password in case of loss (database identification)                                                                    | 1                | Requires email sending to be enabled                                                                         |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.tokenIdentityValidity        | Validity period of the token automatically generated during identification (excluding HEADER). The token allows the user to automatically reconnect as long as the token is valid | 36000 (10 hours) |                                                                                                              |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.adminSessionDuration         | Duration in seconds of the "admin" session's validity. Once the duration expires, the TOTP code is requested again.                                                               | 600 (10 minutes) | Not recommended                                                                                              |
|                                                               |                                                                                                                                                                                   |                  |                                                                                                              |
|                                                               | The counter resets each time an "admin" module is accessed.                                                                                                                       |                  |                                                                                                              |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
| Ppci\Config\IdentificationConfig.GACL_disable_new_right       | If set to 1, the creation of a new right is inhibited                                                                                                                             | 1                | Never. Rights are defined during application development; changing this setting may have undesirable effects |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+--------------------------------------------------------------------------------------------------------------+
:::

::: {.content-visible when-profile="french"}
## Affichage des cartes géographiques

+-------------------------------------+-------------------------------------------------------+-------------------------+----------------------+
| Paramètre                           | Description                                           | Valeur par défaut       | Modifiable dans .env |
+=====================================+=======================================================+=========================+======================+
| Ppci\\Config\\OsmMap.mapSeedMinZoom | Niveau minimal d'affichage du zoom                    | 12                      |                      |
+-------------------------------------+-------------------------------------------------------+-------------------------+----------------------+
| Ppci\\Config\\OsmMap.mapSeedMaxZoom | Niveau maximal d'affichage du zoom                    | 16                      |                      |
+-------------------------------------+-------------------------------------------------------+-------------------------+----------------------+
| Ppci\\Config\\OsmMap.mapSeedMaxAge  | Ancienneté maximale d'une tuile de la carte, en jours | 7                       |                      |
+-------------------------------------+-------------------------------------------------------+-------------------------+----------------------+
| Ppci\\Config\\OsmMap.mapCacheMaxAge | Durée maximale du cache des tuiles                    | 7 \* 24 \* 3600 \* 1000 |                      |
+-------------------------------------+-------------------------------------------------------+-------------------------+----------------------+
:::

::: {.content-visible when-profile="english"}
+-------------------------------------+------------------------------------+-------------------------+------------------------+
| Parameter                           | Description                        | Default                 | Can be changed in .env |
+=====================================+====================================+=========================+========================+
| Ppci\\Config\\OsmMap.mapSeedMinZoom | Minimum zoom display level         | 12                      |                        |
+-------------------------------------+------------------------------------+-------------------------+------------------------+
| Ppci\\Config\\OsmMap.mapSeedMaxZoom | Maximum zoom display level         | 16                      |                        |
+-------------------------------------+------------------------------------+-------------------------+------------------------+
| Ppci\\Config\\OsmMap.mapSeedMaxAge  | Maximum age of a map tile, in days | 7                       |                        |
+-------------------------------------+------------------------------------+-------------------------+------------------------+
| Ppci\\Config\\OsmMap.mapCacheMaxAge | Maximum tile cache duration        | 7 \* 24 \* 3600 \* 1000 |                        |
+-------------------------------------+------------------------------------+-------------------------+------------------------+
:::